name: bottom_animation
description: Flutter Bottom Navigation Bar | if you want bottom navigation with smooth animation add this package .
version: 2.0.0

homepage: https://github.com/mahmoud-eslami/bottom_animation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: